### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by igitur** [forgineer/duckdb-kettle-plugin#3]
Just a kind request to add binary releases for us lazy folk who don't want to build from source. Especially now that DuckDB v1 has been released. 🙏

**Comment by forgineer** [comment]
Wow, thank you for commenting. I'll take another look at this and start providing them soon!

**Comment by forgineer** [comment]
I have created a first release that includes a compiled binary for PDI 9.4 and DuckDB 1.1.0 :)
